### ISSUE TITLE
Motor Control (H-bridges & Motor Drivers)

### ISSUE THREAD

**Issue by StevenLandriault** [Uvic-Robotics-Club/Electrical#6]
Synopsis: Making decisions on how motors are to be controlled in the rovers
Tasks:

- [ ] (research) Determine if a custom H-bridge solution or off the shelf option should be adopted to control DC motors in the Chassis and arm

- [ ] (arm) (research) Decide on the motor drivers used in the stepper motors for the arm. check as to what has been used in the arm previously

**Comment by CyberMufasa** [comment]
Need to determine new mechanical design. Concern is if the mid-joint (big) actuator will be converted into a stepper motor still or left as an actuator. This will determine if its connected to a TB6600 motor driver or not as detailed on the [Robot Arm](https://github.com/Uvic-Robotics-Club/Administrative/wiki/Arm-Overview) page.

**Comment by Robotician1** [comment]
4s rc/hobby speed controllers (https://www.hobbywingdirect.com/collections/quicrun-brushed-system) were originally considered for motor drives but were considered too expensive - perhaps cheaper options are available?

H bridges had been designed for the rover in the past based on parts in Q-hut but there is no supporting documentation. Parts will likely be useful if we chose to re-design h bridge drives.
