### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by StevenLandriault** [Uvic-Robotics-Club/Electrical#7]
Synopsis: Draft a parts list for current inventory in the Q-hut and parts to be ordered
Tasks:

- [ ] (documentation) Draft a parts spreadsheet (Excel)? that can be used for future documentation of inventory when the Q-hut is open
- [ ] (Research) Work with other members to determine the parts that need to be ordered and enter them into the parts list

**Comment by CyberMufasa** [comment]
The link 'Inventory of parts and power draw breakdown' in [Battery And Power
](https://github.com/Uvic-Robotics-Club/Administrative/wiki/Battery-And-Power) on the wiki is an attempt at some inventory.
 So we should clean it up/add on to this linked spreadsheet.
